Fix Linux build when sys_siglist is not declared
On more recent gcc versions (e.g. gcc 11.2.0 bundled with Ubuntu 22.04),
the Linux build fails with:
`
error: ‘sys_siglist’ was not declared in this scope
   74 |   cerr << "ITK-SNAP: " << sys_siglist[sig] << endl;
`

The sys_siglist array has been marked as non-standard, deprecated, and
from glibc version > 2.32 is also no longer exported).

This commit fixes the compilation by replacing the direct "sys_siglist"
array access with calling the strsignal function.

For more info, see:
https://man7.org/linux/man-pages/man3/strsignal.3.html
It has been in the POSIX standard since 2008:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/strsignal.html